from social_django.middleware import SocialAuthExceptionMiddleware
